import React, { useState } from 'react';
import {
  KeyRound,
  Plus,
  ShieldCheck,
  CheckCircle,
} from 'lucide-react';
import { TotpAccount } from '../types/totp';
import { TotpCard } from '../components/authenticator/TotpCard';
import { TotpModal } from '../components/modals/TotpModal';

interface AuthenticatorPageProps {
  accounts: TotpAccount[];
  onAddAccount: (account: TotpAccount) => void;
  onUpdateAccount: (account: TotpAccount) => void;
  onDeleteAccount: (id: string) => void;
}

export const AuthenticatorPage: React.FC<AuthenticatorPageProps> = ({
  accounts,
  onAddAccount,
  onUpdateAccount,
  onDeleteAccount,
}) => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingAccount, setEditingAccount] = useState<TotpAccount | null>(null);
  const [copiedNotification, setCopiedNotification] = useState(false);

  const handleCopySuccess = () => {
    setCopiedNotification(true);
    setTimeout(() => setCopiedNotification(false), 2000);
  };

  const handleOpenAdd = () => {
    setEditingAccount(null);
    setIsModalOpen(true);
  };

  const handleOpenEdit = (account: TotpAccount) => {
    setEditingAccount(account);
    setIsModalOpen(true);
  };

  const handleSaveModal = (account: TotpAccount) => {
    if (editingAccount) {
      onUpdateAccount(account);
    } else {
      onAddAccount(account);
    }
  };

  return (
    <div className="max-w-6xl mx-auto px-4 py-8 space-y-8">
      {/* Top Header Card */}
      <div className="p-6 sm:p-8 rounded-3xl bg-surface border border-surface-border shadow-xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6">
        <div>
          <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-md bg-purple-500/10 text-purple-400 text-xs font-semibold mb-2">
            <KeyRound className="w-3.5 h-3.5" />
            <span>RFC 6238 TOTP AUTHENTICATOR</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
            Authenticator
          </h1>
          <p className="text-xs sm:text-sm text-slate-400 mt-1 max-w-xl">
            Real multi-account 6-digit TOTP generator. Works completely offline using local cryptographic HMAC SHA-1. No sample accounts generated by default.
          </p>
        </div>

        <button
          onClick={handleOpenAdd}
          className="px-5 py-3 rounded-xl bg-purple-600 hover:bg-purple-700 text-white text-xs sm:text-sm font-bold shadow-lg shadow-purple-600/25 transition flex items-center gap-2 shrink-0"
        >
          <Plus className="w-4 h-4" />
          <span>+ ADD AUTHENTICATOR</span>
        </button>
      </div>

      {/* Copy Notification Toast */}
      {copiedNotification && (
        <div className="fixed bottom-6 right-6 z-50 p-4 rounded-2xl bg-emerald-500/90 backdrop-blur text-white text-xs font-bold shadow-2xl flex items-center gap-2 animate-fade-in">
          <CheckCircle className="w-4 h-4" />
          <span>Code copied to clipboard</span>
        </div>
      )}

      {/* Accounts List / Grid */}
      {accounts.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {accounts.map(acc => (
            <TotpCard
              key={acc.id}
              account={acc}
              onDelete={onDeleteAccount}
              onEdit={handleOpenEdit}
              onCopySuccess={handleCopySuccess}
            />
          ))}
        </div>
      ) : (
        <div className="text-center py-20 p-8 rounded-3xl bg-surface border border-dashed border-surface-border space-y-4">
          <div className="w-16 h-16 mx-auto rounded-3xl bg-purple-500/10 text-purple-400 border border-purple-500/20 flex items-center justify-center">
            <KeyRound className="w-8 h-8" />
          </div>
          <div className="space-y-1">
            <h3 className="text-lg font-bold text-white">No Authenticator Accounts Saved</h3>
            <p className="text-xs text-slate-400 max-w-md mx-auto">
              Add your Roblox 2-step verification secret key to generate secure offline 6-digit codes.
            </p>
          </div>
          <button
            onClick={handleOpenAdd}
            className="px-5 py-2.5 rounded-xl bg-purple-600 hover:bg-purple-700 text-white text-xs font-bold shadow transition inline-flex items-center gap-2"
          >
            <Plus className="w-4 h-4" />
            <span>+ ADD AUTHENTICATOR</span>
          </button>
        </div>
      )}

      {/* Add / Edit Modal */}
      <TotpModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onSaveAccount={handleSaveModal}
        initialAccount={editingAccount}
      />
    </div>
  );
};
